version: "3.8"

services:

    db:
        image: mysql:5.7
        container_name: db_linc
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_linc
        depends_on:
            - db
        ports:
            - 3080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_linc
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "3081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_linc
        ports:
          - "1111:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:

